SELECT IDENTIDIER,H_NAME,V_NAME,DATE,ROUND
FROM Match
WHERE DATE >= CURRENT DATE
  AND DATE <= CURRENT DATE + DAYS(3);

SELECT NAME,SHIRT_NUMBER,DETAILED_POSITION_IN_GAME,0 AS ENTERED_TIME,NULL AS LEFT_TIME,0 AS YELLOW_CARD_NUMBER,0 AS RED_CARD_NUMBER
FROM MATCH_PLAYER INNER JOIN PLAYER P on P.PID = MATCH_PLAYER.PID
WHERE MATCH_PLAYER.IDENTIDIER = 10007 AND P.COUNTRY = 'England';

SELECT NAME
FROM PLAYER
EXCEPT
SELECT NAME
FROM MATCH_PLAYER

CREATE VIEW games(identifier,pid) AS
SELECT MATCH.identidier,MATCH_PLAYER.PID
FROM MATCH INNER JOIN MATCH_PLAYER
ON match.IDENTIDIER = MATCH_PLAYER.IDENTIDIER;

with pid_no(pid) AS
(   SELECT pid FROM PLAYER EXCEPT SELECT pid
    FROM MATCH INNER JOIN MATCH_PLAYER ON MATCH.IDENTIDIER = MATCH_PLAYER.IDENTIDIER)
SELECT NAME,GENERAL_POSITION,SHIRT_NUMBER
FROM PLAYER
WHERE PLAYER.PID IN (SELECT * FROM pid_no) AND PLAYER.COUNTRY = 'France';

DROP VIEW games;
DROP VIEW pid_no;


INSERT INTO MATCH_PLAYER (
                          SELECT PID,10007,FALSE AS ATTENDANCE,'00:00:00' AS ENTERED_TIME,'00:00:00' AS LEFT_TIME,GENERAL_POSITION,0 AS YELLOW_CARD_NUMBER,0 AS RED_CARD_NUMBER
                          FROM PLAYER WHERE PLAYER.COUNTRY = 'France' AND PLAYER.SHIRT_NUMBER = 10);
DELETE FROM MATCH_PLAYER WHERE  PID = 9000012;
DELETE FROM MATCH_PLAYER WHERE  PID = 9000013;
UPDATE
