with seatsInfo(identidier,seats_sold) AS
(
    SELECT IDENTIDIER,CAPACITY-AVAILABILITY as DIFFERENCE
    FROM MATCH INNER JOIN STADIUM
    ON MATCH.STADIUM = STADIUM.NAME
)
SELECT h_name,v_name,DATE,round,h_score,v_score,seats_sold
FROM MATCH_RESULT INNER JOIN seatsInfo
ON MATCH_RESULT.IDENTIDIER = seatsInfo.identidier
WHERE MATCH_RESULT.H_NAME = 'England';


CREATE VIEW scoreH(IDENTIDIER,H_NAME,score1) AS
SELECT M.IDENTIDIER ,H_NAME, COUNT(WHO_SCORED) AS score
FROM MATCH INNER JOIN MATCHGOALS M
                      ON MATCH.IDENTIDIER = M.IDENTIDIER
WHERE WHO_SCORED IN (
    SELECT pid
    FROM PLAYER INNER JOIN MATCHGOALS M2 on PLAYER.PID = M2.WHO_SCORED
    WHERE PLAYER.COUNTRY = MATCH.H_NAME
)
GROUP by H_NAME,M.IDENTIDIER;
--------------------------------------------------------
CREATE VIEW scoreV(IDENTIDIER,V_NAME,score2) AS
SELECT M.IDENTIDIER ,V_NAME , COUNT(WHO_SCORED) AS score
FROM MATCH INNER JOIN MATCHGOALS M
                      ON MATCH.IDENTIDIER = M.IDENTIDIER
WHERE WHO_SCORED IN (
    SELECT pid
    FROM PLAYER INNER JOIN MATCHGOALS M2 on PLAYER.PID = M2.WHO_SCORED
    WHERE PLAYER.COUNTRY = MATCH.V_NAME
)
GROUP by V_NAME,M.IDENTIDIER;

SELECT MATCH.H_NAME,score1
FROM MATCH LEFT JOIN scoreH ON MATCH.IDENTIDIER = scoreH.IDENTIDIER
UNION ALL
SELECT MATCH.V_NAME,score2
FROM MATCH LEFT JOIN scoreV ON MATCH.IDENTIDIER = scoreV.IDENTIDIER;

------------------------------------------------------------------------
CREATE VIEW tem_score1(hname,score_1) AS
SELECT MATCH.H_NAME,score1
FROM MATCH LEFT JOIN scoreH ON MATCH.IDENTIDIER = scoreH.IDENTIDIER;

CREATE VIEW tem_score2(vname,score_2) AS
SELECT MATCH.V_NAME,score2
FROM MATCH LEFT JOIN scorev ON MATCH.IDENTIDIER = scoreV.IDENTIDIER;

SELECT hname AS H_home, vname AS V_home, score_1, score_2
FROM (
         SELECT hname, score_1, ROW_NUMBER() OVER (ORDER BY hname) AS row_num
         FROM tem_score1
     ) t1
         FULL OUTER JOIN (
    SELECT vname, score_2, ROW_NUMBER() OVER (ORDER BY vname) AS row_num
    FROM tem_score2
) t2 ON t1.row_num = t2.row_num;



SELECT h_name,v_name,DATE,ROUND,h_score,v_score
FROM MATCH INNER JOIN MATCHGOALS M
ON MATCH.IDENTIDIER = M.IDENTIDIER;

SELECT *
FROM REFEREES
WHERE REFEREES.RID = 1001;

